2022-02-01 21:46:39,224 INFO father parents provide 10 cacolate
2022-02-01 21:46:39,224 INFO Number of cacolate child get from father is 10
2022-02-01 21:46:39,224 INFO father parents provide 10 cacolate
2022-02-01 21:46:39,224 INFO Number of cacolate child get from mother is 10
2022-02-01 21:46:39,224 INFO Total number of coco is 100
2022-02-01 22:01:05,731 INFO father parents provide 10 cacolate
2022-02-01 22:01:05,732 INFO Number of cacolate child get from father is 10
2022-02-01 22:01:05,732 INFO father parents provide 10 cacolate
2022-02-01 22:01:05,732 INFO Number of cacolate child get from mother is 10
2022-02-01 22:01:05,732 INFO Total number of coco is 100
2022-02-01 22:01:37,173 INFO father parents provide 10 cacolate
2022-02-01 22:01:37,173 INFO Number of cacolate child get from father is 10
2022-02-01 22:01:37,174 INFO father parents provide 10 cacolate
2022-02-01 22:01:37,174 INFO Number of cacolate child get from mother is 10
2022-02-01 22:01:37,174 INFO Total number of coco is 100
2022-02-01 22:02:18,558 ERROR System have more error
2022-02-01 22:04:02,065 ERROR System have more error
2022-02-01 22:04:59,660 ERROR System have more error
2022-02-01 22:04:59,662 ERROR System have more error
2022-02-01 22:04:59,664 ERROR Number of error available 6 
Traceback (most recent call last):
  File "customexception.py", line 22, in nooferrorhappen
    raise(customexception("System  have more exception ", self.nooferrormessage ))
customexception: ('System  have more exception ', 6)
